measure: 
  key: invoice
  name: Invoices
  aggregation: sum_of_invoices
filters:
- key: customer
  contextual_filters:
    - for_customer
- c_date
dimensions:
- monthly_group
- key: customer
  limit: 5
chart:
  options:
    scales:
      xAxes:
        - stacked: true
      yAxes:
        - stacked: true