measure: 
  key: invoice
  name: Invoices
  aggregation: sum_of_invoices
filters:
- c_date
- key: customer
  contextual_filters:
    - for_customer
dimensions:
- key: customer
  limit: 5
- c_date
chart:
  options:
    scales:
      xAxes:
        - stacked: true
      yAxes:
        - stacked: true


